{% set name = "fast_vindex" %}
{% set version = "0.0.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a66751f9943151b4f1158f73d6882666d36da037e79596c9b09ed9660d0387b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - dask >=2025.1.0
    - matplotlib-base >=3.8
    - numpy >=1.26
    - pandas >=2.2
    - xarray >=2024.10.0

test:
  imports:
    - fast_vindex
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.ifremer.fr/odatis-public/fast_vindex
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: "A faster version of Dask's vindex for advanced indexing with arrays."

extra:
  recipe-maintainers:
    - GwenaelCaer
